// redisClient.js — a single shared ioredis connection.
// This is already wired for you. Do NOT edit this file.
import Redis from "ioredis";

export const redis = new Redis(process.env.REDIS_URL || "redis://127.0.0.1:6379");

redis.on("error", (err) => {
  console.error("Redis connection error:", err.message);
});
